config/routes.rb
Rails.application.routes.draw do
  root 'page#index'
  get  'find'     => 'page#find'
  post 'search'   => 'page#search'
  post 'sendmail' => 'page#sendmail'
  get  'test'     => 'page#test'
  get  'help'     => 'page#help'
  get  'results'  => 'page#results'
  get  'reminder' => 'page#reminder'
  post 'reminder' => 'page#remind'
  get  'preview' => 'page#preview'

  devise_for :users
  resource :user

  resources :districts
  resources :provinces do
    resources :districts
  end
  resources :regions do
    resources :provinces
    resources :districts
  end

  resources :answers
  resources :picks
  resources :alternatives
  resources :statutes
  resources :contacts
  resources :schools
  resources :questions
  resources :educations
  resources :polls do
    get 'answer' => 'polls#answer', as: :answer
  end
  resources :products do
    resources :batches, only: [:index, :show] do
      post 'reminder', on: :member
    end
    
    member do
      get 'results'
      get 'download'
    end
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :poll
  has_many :alternatives, inverse_of: :question

  delegate :to_s, to: :statement
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @questions = Question.includes(:alternatives).all
    respond_with(@questions)
  end

  def show
    respond_with(@question)
  end

  def new
    @question = Question.new
    respond_with(@question)
  end

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.save
    respond_with(@question)
  end

  def update
    @question.update(question_params)
    respond_with(@question)
  end

  def destroy
    @question.destroy
    respond_with(@question)
  end

  private
    def set_question
      @question = Question.includes(:alternatives).find(params[:id])
    end

    def question_params
      params.require(:question).permit(:poll_id, :statement)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= simple_form_for(@question) do |f|
  = f.error_notification

  .form-inputs
    = f.association :poll
    = f.input :number
    = f.input :statement

  .form-actions
    = f.button :submit

app/views/questions/_question.html.slim
h4
  = question.number
  | . &nbsp;
  = question.statement
.row
  = f.fields_for "q#{question.id}".to_sym do |p|
    ul.no-bullet
      = p.collection_radio_buttons :alternative_id, question.alternatives, :id, :statement do |o|
          li= o.radio_button + o.text

app/views/questions/edit.html.slim
h1 Editing question

== render 'form'

= link_to 'Show', @question
'|
= link_to 'Back', questions_path

app/views/questions/index.html.slim
h1 Listing questions

table.table
  thead
    tr
      th Poll
      th Statement
      th
      th
      th

  tbody
    - @questions.each do |question|
      tr
        td = question.poll
        td
          strong = question.statement
        td = link_to 'Show', question
        td = link_to 'Edit', edit_question_path(question)
        td = link_to 'Destroy', question, data: { confirm: 'Are you sure?' }, method: :delete

        - question.alternatives.each do |alternative|
          tr
            td = alternative.number
            td = alternative.statement
            td = link_to 'Show', alternative
            td = link_to 'Edit', edit_alternative_path(alternative)
            td = link_to 'Destroy', alternative, data: { confirm: 'Are you sure?' }, method: :delete


br

= link_to 'New Question', new_question_path

app/views/questions/new.html.slim
h1 New question

== render 'form'

= link_to 'Back', questions_path

app/views/questions/show.html.slim
p#notice = notice

p
  strong Poll:
  = @question.poll
p
  strong Statement:
  = @question.statement

= link_to 'Edit', edit_question_path(@question)
'|
= link_to 'Back', questions_path