config/routes.rb
Rails.application.routes.draw do
  root 'page#index'
  get  'find'     => 'page#find'
  post 'search'   => 'page#search'
  post 'sendmail' => 'page#sendmail'
  get  'test'     => 'page#test'
  get  'help'     => 'page#help'
  get  'results'  => 'page#results'
  get  'reminder' => 'page#reminder'
  post 'reminder' => 'page#remind'
  get  'preview' => 'page#preview'

  devise_for :users
  resource :user

  resources :districts
  resources :provinces do
    resources :districts
  end
  resources :regions do
    resources :provinces
    resources :districts
  end

  resources :answers
  resources :picks
  resources :alternatives
  resources :statutes
  resources :contacts
  resources :schools
  resources :questions
  resources :educations
  resources :polls do
    get 'answer' => 'polls#answer', as: :answer
  end
  resources :products do
    resources :batches, only: [:index, :show] do
      post 'reminder', on: :member
    end
    
    member do
      get 'results'
      get 'download'
    end
  end

end

app/views/page/find.html.slim
div class="row"
	aside class="col-md-4"
		h3 Enviar encuesta

		= simple_form_for :search, url: search_path do |f|
		  = f.input :max,       label:'Número de encuestados',  as: :integer,       required: true, default: 100
		  = f.input :region,    label:'Región',					   collection: @regions,    required: false, input_html: { onchange: 'load_districts(this)' }
		  = f.input :district,  label:'Comuna',					   collection: @districts,  required: false, input_html: { id: 'districts'}
		  = f.input :statute,   label:'Dependencia',			 collection: @statutes,   required: false
		  = f.input :education, label:'Tipo de educación', collection: @educations, required: false
		  = f.input :product,   label:'Producto',				   collection: @products,	  required: true

		  = f.submit "Enviar", class: 'btn btn-primary'

	div class="col-md-7" id="preview"
		h1 Previsualización
		iframe src="mails/preview" style="width:600px; height:700px;" frameborder="0"

app/views/page/help.html.slim
p Ayuda

app/views/page/index.html.slim
- if !user_signed_in? then
	div class="center jumbotron"
		h3 Bienvenido al 
		h1 Sistema de Gestión del Usuario
		= link_to "Ingresar", new_user_session_path, class: "btn btn-lg btn-primary"

- else
	div class="row"
		div class="col-md-2"
		div class="col-md-1"
			= image_tag "flecha1.png"
		div class="col-md-1"
			= image_tag "flecha2.png"
		div class="col-md-1"
			= image_tag "flecha3.png"
	div class="row"
		div class="col-md-1"
		div class="col-md-3"
			h1 Mapa
			p class="parrafo" En esta sección podrás cargar los porductos, indicando:
			ul class="custom-bullet"
				li Nombre del Producto
				li Link
				li Descripción
				li Extensión del Prodructo
				li Objetivo del Producto
				li Comprensión del Producto
			p class="parrafo" Adicionalmente, existe un gráfico que te ayudará a comprender las características que tienen los productos que se han cargado en el sistema.
		div class="col-md-1"	
		div class="col-md-3"
			h1 Encuestar
			p class="parrafo" En esta sección podrás enviar encuestas, que serán dirigidas a los directores de los establecimientos que estén dentro del espectro de los filtros que elegiste.
		div class="col-md-1"
		div class="col-md-3"
			h1 Resultados
			p class="parrafo" En esta sección podrás revisar las respuestas que se han generado para un producto específico, además, están a tu disposición los indicadores de desempeño del producto, incluyendo sintonía, facilidad de uso y utilidad.
			p class="parrafo" Además es posible filtrar las respuestas según alguna de las siguientes condiciones:
			ul class="custom-bullet"
				li Región
				li Comuna
				li Dependencia
				li Tipo de Educación

app/views/page/preview.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!--[if !mso]><!--><meta http-equiv="X-UA-Compatible" content="IE=edge" /><!--<![endif]-->
    <meta name="viewport" content="width=device-width" />
    <title> </title>
    <style type="text/css">
.btn a:hover,
.footer__links a:hover {
  opacity: 0.8;
}
.wrapper .footer__share-button:hover {
  color: #ffffff !important;
  opacity: 0.8;
}
a[x-apple-data-detectors] {
  color: inherit !important;
  text-decoration: none !important;
  font-size: inherit !important;
  font-family: inherit !important;
  font-weight: inherit !important;
  line-height: inherit !important;
}
.column {
  padding: 0;
  text-align: left;
  vertical-align: top;
}
.mso .font-avenir,
.mso .font-cabin,
.mso .font-open-sans,
.mso .font-ubuntu {
  font-family: sans-serif !important;
}
.mso .font-bitter,
.mso .font-merriweather,
.mso .font-pt-serif {
  font-family: Georgia, serif !important;
}
.mso .font-lato,
.mso .font-roboto {
  font-family: Tahoma, sans-serif !important;
}
.mso .font-pt-sans {
  font-family: "Trebuchet MS", sans-serif !important;
}
.mso .footer p {
  margin: 0;
}
@media only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min--moz-device-pixel-ratio: 2), only screen and (-o-min-device-pixel-ratio: 2/1), only screen and (min-device-pixel-ratio: 2), only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) {
  .fblike {
    background-image: url(https://i7.createsend1.com/static/eb/customise/13-the-blueprint-3/images/fblike@2x.png) !important;
  }
  .tweet {
    background-image: url(https://i8.createsend1.com/static/eb/customise/13-the-blueprint-3/images/tweet@2x.png) !important;
  }
  .linkedinshare {
    background-image: url(https://i9.createsend1.com/static/eb/customise/13-the-blueprint-3/images/lishare@2x.png) !important;
  }
  .forwardtoafriend {
    background-image: url(https://i4.createsend1.com/static/eb/customise/13-the-blueprint-3/images/forward@2x.png) !important;
  }
}
@media only screen and (max-width: 620px) {
  .wrapper .size-18,
  .wrapper .size-20 {
    font-size: 17px !important;
    line-height: 26px !important;
  }
  .wrapper .size-22 {
    font-size: 18px !important;
    line-height: 26px !important;
  }
  .wrapper .size-24 {
    font-size: 20px !important;
    line-height: 28px !important;
  }
  .wrapper .size-26 {
    font-size: 22px !important;
    line-height: 31px !important;
  }
  .wrapper .size-28 {
    font-size: 24px !important;
    line-height: 32px !important;
  }
  .wrapper .size-30 {
    font-size: 26px !important;
    line-height: 34px !important;
  }
  .wrapper .size-32 {
    font-size: 28px !important;
    line-height: 36px !important;
  }
  .wrapper .size-34,
  .wrapper .size-36 {
    font-size: 30px !important;
    line-height: 38px !important;
  }
  .wrapper .size-40 {
    font-size: 32px !important;
    line-height: 40px !important;
  }
  .wrapper .size-44 {
    font-size: 34px !important;
    line-height: 43px !important;
  }
  .wrapper .size-48 {
    font-size: 36px !important;
    line-height: 43px !important;
  }
  .wrapper .size-56 {
    font-size: 40px !important;
    line-height: 47px !important;
  }
  .wrapper .size-64 {
    font-size: 44px !important;
    line-height: 50px !important;
  }
  .divider {
    Margin-left: auto !important;
    Margin-right: auto !important;
  }
  .btn a {
    display: block !important;
    font-size: 14px !important;
    line-height: 24px !important;
    padding: 12px 10px !important;
    width: auto !important;
  }
  .btn--shadow a {
    padding: 12px 10px 13px 10px !important;
  }
  .image img {
    height: auto;
    width: 100%;
  }
  .layout,
  .column,
  .preheader__webversion,
  .header td,
  .footer,
  .footer__left,
  .footer__right,
  .footer__inner {
    width: 320px !important;
  }
  .preheader__snippet,
  .layout__edges {
    display: none !important;
  }
  .preheader__webversion {
    text-align: center !important;
  }
  .layout--full-width {
    width: 100% !important;
  }
  .layout--full-width tbody,
  .layout--full-width tr {
    display: table;
    Margin-left: auto;
    Margin-right: auto;
    width: 320px;
  }
  .column,
  .layout__gutter,
  .footer__left,
  .footer__right {
    display: block;
    Float: left;
  }
  .footer__inner {
    text-align: center;
  }
  .footer__links {
    Float: none;
    Margin-left: auto;
    Margin-right: auto;
  }
  .footer__right p,
  .footer__share-button {
    display: inline-block;
  }
  .layout__gutter {
    font-size: 20px;
    line-height: 20px;
  }
  .layout--no-gutter.layout--has-border:not(.layout--full-width),
  .layout--has-gutter.layout--has-border .column__background {
    width: 322px !important;
  }
  .layout--has-gutter.layout--has-border {
    left: -1px;
    position: relative;
  }
}
@media only screen and (max-width: 320px) {
  .border {
    display: none;
  }
  .layout--no-gutter.layout--has-border:not(.layout--full-width),
  .layout--has-gutter.layout--has-border .column__background {
    width: 320px !important;
  }
  .layout--has-gutter.layout--has-border {
    left: 0 !important;
  }
}
</style>
    
  <!--[if !mso]><!--><style type="text/css">
@import url(https://fonts.googleapis.com/css?family=Merriweather:400italic,400,700,700italic|Open+Sans:400italic,700italic,700,400);
</style><link href="https://fonts.googleapis.com/css?family=Merriweather:400italic,400,700,700italic|Open+Sans:400italic,700italic,700,400" rel="stylesheet" type="text/css" /><!--<![endif]--><style type="text/css">
body,.wrapper{background-color:#eff0ed}.wrapper h1{color:#99a389;font-size:26px;line-height:34px}.wrapper h2{color:#99a389;font-size:20px;line-height:28px}.wrapper h3{color:#c4b5ac;font-size:16px;line-height:24px}.wrapper h3{}.wrapper h3{font-family:"Open Sans",sans-serif}.mso .wrapper h3{font-family:sans-serif !important}.wrapper a{color:#00afd1}.wrapper a:hover{color:#005a6b !important}@media only screen and (max-width: 620px){.wrapper h1{}.wrapper h1{font-size:22px;line-height:31px}.wrapper h2{}.wrapper h2{font-size:17px;line-height:26px}.wrapper h3{}.wrapper p{}}.column,.column__background td{color:#808285;font-size:14px;line-height:21px}.column,.column__background td{font-family:Merriweather,Georgia,serif}.mso .column,.mso .column__background td{font-family:Georgia,serif 
!important}.border{background-color:#bec2b5}.layout--no-gutter.layout--has-border:not(.layout--full-width),.layout--has-gutter.layout--has-border .column__background,.layout--full-width.layout--has-border{border-top:1px solid #bec2b5;border-bottom:1px solid #bec2b5}.wrapper blockquote{border-left:4px solid #bec2b5}.divider{background-color:#bec2b5}.wrapper .btn a{color:#fff}.wrapper .btn a{font-family:Merriweather,Georgia,serif}.mso .wrapper .btn a{font-family:Georgia,serif !important}.wrapper .btn a:hover{color:#fff !important}.btn--flat a,.btn--shadow a,.btn--depth a{background-color:#a6bf7a}.btn--ghost a{border:1px solid #a6bf7a}.preheader--inline,.footer__left{color:#968f8b}.preheader--inline,.footer__left{font-family:"Open Sans",sans-serif}.mso .preheader--inline,.mso .footer__left{font-family:sans-serif !important}.wrapper .preheader--inline a,.wrapper .footer__left 
a{color:#968f8b}.wrapper .preheader--inline a:hover,.wrapper .footer__left a:hover{color:#968f8b !important}.header__logo{color:#c3ced9}.header__logo{font-family:Roboto,Tahoma,sans-serif}.mso .header__logo{font-family:Tahoma,sans-serif !important}.wrapper .header__logo a{color:#c3ced9}.wrapper .header__logo a:hover{color:#859bb1 !important}.footer__share-button{background-color:#787877}.footer__share-button{font-family:"Open Sans",sans-serif}.mso .footer__share-button{font-family:sans-serif !important}.layout__separator--inline{font-size:20px;line-height:20px;mso-line-height-rule:exactly}
</style><meta name="robots" content="noindex,nofollow" />
<meta property="og:title" content="My First Campaign" />
</head>
<!--[if mso]>
  <body class="mso">
<![endif]-->
<!--[if !mso]><!-->
  <body class="full-padding" style="margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #eff0ed;">
<!--<![endif]-->
    <div class="wrapper" style="background-color: #eff0ed;">
      <table style='border-collapse: collapse;table-layout: fixed;color: #968f8b;font-family: "Open Sans",sans-serif;' align="center">
        <tbody><tr>
          <td class="preheader__snippet" style="padding: 10px 0 5px 0;vertical-align: top;width: 280px;">
            
          </td>
          <td class="preheader__webversion" style="text-align: right;padding: 10px 0 5px 0;vertical-align: top;width: 280px;">
            
          </td>
        </tr>
      </tbody></table>
      <table class="header" style="border-collapse: collapse;table-layout: fixed;Margin-left: auto;Margin-right: auto;" align="center" id="emb-email-header-container">
        <tbody><tr>
          <td style="padding: 0;width: 600px;">
            <div class="header__logo emb-logo-margin-box" style="font-size: 26px;line-height: 32px;Margin-top: 5px;Margin-bottom: 5px;color: #c3ced9;font-family: Roboto,Tahoma,sans-serif;Margin-left: 20px;Margin-right: 20px;">
              <div class="logo-center" style="font-size:0px !important;line-height:0 !important;" align="center" id="emb-email-header"><img style="height: auto;width: 50%;border: 0;max-width: 128px;" src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Logotipo_de_la_Agencia_de_Calidad_de_la_Educación.png/245px-Logotipo_de_la_Agencia_de_Calidad_de_la_Educación.png" alt=""  /></div>
            </div>
          </td>
        </tr>
      </tbody></table>
      <table class="layout layout--no-gutter layout--full-width" style="border-collapse: collapse;table-layout: fixed;Margin-left: auto;Margin-right: auto;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;width: 100%;background-color: #ffffff;" align="center" emb-background-style>
        <tbody><tr>
          <td class="layout__edges" style="font-size: 0;">&nbsp;</td>
          <td class="column" style="padding: 0;text-align: left;vertical-align: top;color: #808285;font-size: 14px;line-height: 21px;font-family: Merriweather,Georgia,serif;width: 600px;">
        
            <div style="Margin-left: 20px;Margin-right: 20px;Margin-top: 5px;">
      <div style="line-height:20px;font-size:1px">&nbsp;</div>
    </div>
        
        
        <div class="image" style="font-size: 12px;font-style: normal;font-weight: 400;" align="center">
          <img style="display: block;border: 0;max-width: 324px;" src="http://famaranon.com/mail_agencia/image296.png" alt="" width="243" height="85" />
        </div>

        <div style="Margin-left: 20px;Margin-right: 20px;">
      <h1 style="Margin-top: 0;Margin-bottom: 0;font-style: normal;font-weight: normal;color: #99a389;font-size: 26px;line-height: 34px;text-align: center;">&nbsp;</h1><p style="Margin-top: 0px;Margin-bottom: 20px;">Estimada dirección de la institución «Colegio de pruebas» </p>
    </div>
        
            <div style="Margin-left: 20px;Margin-right: 20px;">
      <p style="Margin-top: 0;Margin-bottom: 0;text-align: justify;">  Necesitamos conocer su percepción sobre el «Nombre del producto» a través de cinco breves preguntas.</p><p style="Margin-top: 20px;Margin-bottom: 20px;text-align: justify;">Gracias a sus respuestas podremos mejorar el material que les entregamos.</p>
    </div>
        
            <div style="Margin-left: 20px;Margin-right: 20px;">
      <div class="btn btn--flat" style="Margin-bottom: 20px;text-align: center;">
        <![if !mso]><a style="border-radius: 4px;display: inline-block;font-weight: bold;text-align: center;text-decoration: none !important;transition: opacity 0.1s ease-in;color: #fff;background-color: #808285;font-family: Merriweather, Georgia, serif;font-size: 14px;line-height: 24px;padding: 12px 35px;" href="<%= @url %>" data-width="70">Participar</a><![endif]>
     </div>
    </div>
        
            <div style="Margin-left: 20px;Margin-right: 20px;Margin-bottom: 24px;">
      <div style="line-height:5px;font-size:1px">&nbsp;</div>
    </div>
        
          </td>
          <td class="layout__edges" style="font-size: 0;">&nbsp;</td>
        </tr>
      </tbody></table>
  
      <div style="font-size: 30px;line-height: 30px;mso-line-height-rule: exactly;">&nbsp;</div>
    
      <table class="footer" style="border-collapse: collapse;table-layout: fixed;Margin-right: auto;Margin-left: auto;border-spacing: 0;width: 560px;" align="center">
        <tbody><tr>
          <td style="padding: 0 0 40px 0;">
            <table class="footer__right" style="border-collapse: collapse;table-layout: auto;border-spacing: 0;" align="right">
              <tbody><tr>
                <td class="footer__inner" style="padding: 0;">
                  
                  
                  
                  
                </td>
              </tr>
            </tbody></table>
            <table class="footer__left" style='border-collapse: collapse;table-layout: fixed;border-spacing: 0;color: #968f8b;font-family: "Open Sans",sans-serif;width: 380px;'>
              <tbody><tr>
                <td class="footer__inner" style="padding: 0;font-size: 12px;line-height: 19px;">
                  <table class="footer__links emb-web-links" style="border-collapse: collapse;table-layout: fixed;"><tbody><tr>
                    </tr></tbody></table>
                  <div style="Margin-top: 26px;">
                    
                  </div>
                  <div class="footer__permission" style="Margin-top: 18px;">
                    
                  </div>
                </td>
              </tr>
            </tbody></table>
          </td>
        </tr>
      </tbody></table>
      
    </div>
  
</body></html>

app/views/page/reminder.html.slim
= form_for :reminder do |f|
  = f.select :product, options_from_collection_for_select(@products, :slug, :name)

  = f.submit "Ir a"

app/views/page/results.html.slim
h3 = @product.try :name

.row
  .col-xs-4
    h3 class="results" Objetivo
    scatter-chart(name="base", data=prepare_data([@base]))

  .col-xs-4
    h3 Métricas
    gauge-chart(name="synth", data=prepare_gauge(@base, @answers))

  .col-xs-4
    h3 class="results"
      | Resultado &nbsp;
      = "(#{@answers.count})"
    scatter-chart(name="results", data=prepare_data(@answers))

    .download
      = link_to "Descargar", download_product_path(@product), class: "btn btn-primary" if @product

.row
  .col-md-4

  .col-md-4
    = simple_form_for :results, url: results_path, method: :get do |f|
      = f.input :product,   label: 'Producto',         collection: @products,   required: false, value_method: :slug
      hr
      = f.input :region,    label: 'Región',            collection: @regions,    required: false, input_html: { onchange: 'load_districts(this)' }
      = f.input :district,  label:'Comuna',            collection: @districts,  required: false, input_html: { id: 'districts'}
      = f.input :statute,   label:'Dependencia',       collection: @statutes,   required: false
      = f.input :education, label:'Tipo de educación', collection: @educations, required: false
      hr
      = f.input :from, label: "Desde"
      = f.input :to,   label: "Hasta"
      
      = submit_tag "Ver" , class: 'btn btn-primary'

  .col-md-4
    = image_tag "simbologia.png", class: "sybology_image_results"

app/views/page/search.html.slim
= form_for :poll, url: sendmail_path do |f|
  = f.hidden_field :product_id, value: @product.id
  h2 = @product.name

  = f.collection_check_boxes :contacts, @contacts, :id, :full_name do |b|
    div.col-md-3.col-xs-4 = b.check_box({checked: true}) + b.text

  = f.submit 'Enviar Encuesta', class: 'btn btn-primary'
  = link_to "Cancelar", root_path, class: 'btn btn-default margin-top'

app/views/page/test.html.slim
gauge-chart(name="thisone" data=[10,30,75])
scatter-chart(name="thatone" data=prepare_data(@answers))