config/routes.rb
Rails.application.routes.draw do
  root 'page#index'
  get  'find'     => 'page#find'
  post 'search'   => 'page#search'
  post 'sendmail' => 'page#sendmail'
  get  'test'     => 'page#test'
  get  'help'     => 'page#help'
  get  'results'  => 'page#results'
  get  'reminder' => 'page#reminder'
  post 'reminder' => 'page#remind'
  get  'preview' => 'page#preview'

  devise_for :users
  resource :user

  resources :districts
  resources :provinces do
    resources :districts
  end
  resources :regions do
    resources :provinces
    resources :districts
  end

  resources :answers
  resources :picks
  resources :alternatives
  resources :statutes
  resources :contacts
  resources :schools
  resources :questions
  resources :educations
  resources :polls do
    get 'answer' => 'polls#answer', as: :answer
  end
  resources :products do
    resources :batches, only: [:index, :show] do
      post 'reminder', on: :member
    end
    
    member do
      get 'results'
      get 'download'
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  extend FriendlyId

  belongs_to :user
  belongs_to :answer
  has_many :answers, inverse_of: :product
  has_many :batches, inverse_of: :product
  has_many :picks,        through: :answers
  has_many :alternatives, through: :picks
  has_many :questions,    through: :alternatives
  has_many :schools,      through: :answers
  has_many :contacts, through: :batches

  friendly_id :name, use: :slugged

  delegate :to_s, to: :name

  def long_persisted?
    persisted? and created_at + 10.minutes < Time.now
  end

  def to_csv
    CSV.generate do |csv|
      padding = [nil] * questions.distinct.count
      
      csv << [name] + padding
      csv << [] + padding

      csv << School.to_title_row + ["Contact"] + questions.order(:number).distinct.map(&:statement) + ["Date"]
      answers.includes(school: [:region, :statute, :education], picks: [:alternative]).last([answers.length.pred, 0].max).each do |answer|
        entries = answer
          .picks
          .map(&:alternative)
          .sort_by(&:question_id)
          .map(&:statement)

        csv << (answer.school_to_row || []) + [answer.contact_email] + entries + [(I18n.l answer.created_at, format: :short)]
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_questions, only: [:new, :edit, :create, :update]
  #load_and_authorize_resource find_by: :slug

  respond_to :html

  def index
    @products = Product.includes(:user).all
    respond_with(@products)
  end

  def show
    respond_with(@product)
  end

  def new
    @product = Product.new
    @answers = Answer.includes(picks: [alternative: :question]).internal
    respond_with(@product)
  end

  def edit
  end

  def create
    @product          = current_user.products.new(bare_product_params)
    @product.answer   = Answerable.process(product_params[:answer].merge(product_id: @product.id))
    @product.answers << @product.answer
    
    @product.save
    respond_with(@product)
  end

  def update
    @product.update(product_params)
    respond_with(@product)
  end

  def destroy
    @product.destroy
    respond_with(@product)
  end

  def results
    @product = Product.friendly.find params[:id]
    @base    = @product
      .answers
      .includes(picks: [alternative: :question])
      .internal
      .first

    @answers = @product
      .answers
      .includes(picks: [alternative: :question])
      .external
  end

  def download
    @product = Product.includes(answers: [:school, picks: [alternative: :question]]).friendly.find params[:id]

    render csv: @product
  end

  private
    def set_product
      @product = Product.friendly.find(params[:id])
    end

    def set_questions
      @questions = Question.includes(:alternatives).where(id: [1,3,4])
    end

    def bare_product_params
      params.require(:product).permit(:name, :link, :description, :slug)
    end

    def product_params
      answer_params = [q1: [:alternative_id], q3: [:alternative_id], q4: [:alternative_id]]
      params.require(:product).permit(:name, :link, :description, :slug, answer: answer_params)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.slim
= simple_form_for(@product) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, label:'Nombre del Producto', readonly: @product.long_persisted?
    = f.input :link, label:'Link'
    = f.input :description, label:'Descripción'

  .form-inputs
    = f.fields_for :answer do |a|
      - @questions.each do |question|
        = a.fields_for "q#{question.id}".to_sym do |p|
          = p.input :alternative_id, label: question.statement, collection: question.alternatives, required: false

  .form-actions
    = f.submit "Cargar", class: 'btn btn-primary'

app/views/products/edit.html.slim
h1
  | Editando&nbsp;
  = @product.name

== render 'form'

= link_to 'Show', @product
'|
= link_to 'Back', products_path

app/views/products/index.html.slim
h1 Lista de Productos

table.table
  thead
    tr
      th Creado por
      th Nombre de Producto
      th Link
      th Descripción
      th
      th
      th

  tbody
    - @products.each do |product|
      tr
        td = product.user
        td = product.name
        td = link_to product.link, product.link
        td = product.description
        td = link_to 'Ver', product
        td = link_to 'Editar', edit_product_path(product)
        td = link_to 'Eliminar', product, data: { confirm: 'Estas seguro que lo quieres eliminar ?' }, method: :delete

br

= link_to 'Cargar Producto', new_product_path

app/views/products/new.html.slim
div class="row"
aside class="col-md-4"
  h3 Cargar producto
  == render 'form'
  br
  = link_to 'Lista de Productos',products_path, class: 'btn btn-primary btn-block'

div class="col-md-7" id="preview"
  h3 Mapa de Productos
  scatter-chart(name="existing", data=prepare_data(@answers))
  = image_tag "simbologia.png", class: "sybology_image"

app/views/products/results.html.slim
h1 = @product.name

scatter-chart(name="initial", data=prepare_data(@base))
gauge-chart(name="synth",     data=prepare_gauge(@base, @answers))
scatter-chart(name="total",   data=prepare_data(@answers))

= form_tag results_product_path(@product), method: :get do
  = date_field_tag :from
  = date_field_tag :to
  
  = submit_tag

#result style="width:600px; height:400px;"

app/views/products/show.html.slim
h1 #notice = notice

div class="row"
aside class="col-md-4"
  	h4 Nombre del producto
  	h2 = @product.name
  	h4 Link del producto
  	h2.lead = link_to @product.link
  	h4 Descripción del producto	
  	h2 = simple_format @product.description

div class="col-md-7" id="preview"
  h3 Mapa
  scatter-chart(name="init_data", data=prepare_data(@product.answers.internal).to_json)
  = image_tag "simbologia.png", class: "sybology_image"

= link_to 'Edit', edit_product_path(@product), class: 'btn btn-primary'
| &nbsp;
= link_to 'Back', new_product_path